export const tiers = {
    tier1: { // 12 €
        "CA": "Canada",
        "IM": "Ile de Man",
        "JE": "Jersey",
        "KW": "Koweit",
        "CH": "Suisse",
        "US": "Etats-Unis d’Amérique"
    },

    tier2: { // 16.5 €
        "AU": "Australie",
        "BR": "Brésil",
        "GG": "Guernesey",
        "IN*": "Inde",
        "MU": "Maurice",
        "MX": "Mexique",
        "NZ": "Nouvelle-Zélande",
        "PH": "Philippines",
        "QA": "Qatar",
        "RU": "Fédération de Russie"
    },

    tier3: { // 22.5 €
        "AI": "Aguilla",
        "AL": "Albania",
        "AD": "Andorra",
        "AO": "Angola",
        "AG": "Antigua and Baruda",
        "AM": "Armenia",
        "AW": "Aruba",
        "AZ": "Azerbaijan",
        "BS": "Bahamas",
        "BH": "Bahrain",
        "BD": "Bangladesh",
        "BB": "Barbados",
        "BY": "Belarus",
        "BZ": "Belize",
        "BJ": "Benin",
        "BM": "Bermuda",
        "BT": "Bhutan",
        "BO": "Bolivia",
        "BQ": "Bonaire, Saint Eustatius and Saba",
        "BA": "Bosnia and Herzegovina",
        "BW": "Botswana",
        "BN": "Brunei Darussalam",
        "BF": "Burkina Faso",
        "BI": "Burundi",
        "CV": "Cabo Verde",
        "KH": "Cambodia",
        "CM": "Cameroon",
        "KY": "Cayman Islands",
        "TD": "Chad",
        "CN": "China",
        "CO": "Colombia",
        "CK": "Cook Islands",
        "CR": "Costa Rica",
        "HR": "Croatia",
        "CW": "Curacao",
        "DM": "Dminica",
        "DO": "Dominican Republic",
        "EC": "Ecuador",
        "SV": "El Salvador",
        "GQ": "Equitorial Guinea",
        "FJ": "Fiji",
        "PF": "French Polynesia",
        "GA": "Gabon",
        "GM": "Gambia",
        "GE": "Georgia",
        "GH": "Ghana",
        "GL": "Greenland",
        "GD": "Grenada",
        "GP": "Guadeloupe",
        "GT": "Guatemala",
        "GY": "Guyana",
        "HT": "Haiti",
        "HN": "Honduras",
        "HK": "Hong Kong",
        "JM": "Jamaica",
        "KZ": "Kazakhstan",
        "KI": "Kiribati",
        "LA": "Lao People's Democratic Republic",
        "LB": "Lebanon",
        "MO": "Macao",
        "MK": "Macedonia, the former Yugoslav Rebulic of",
        "MG": "Madagascar",
        "MY": "Malaysia",
        "MV": "Maldives",
        "ML": "Mali",
        "MD": "Moldova, Republic of",
        "MN": "Mongolia",
        "ME": "Montenegro",
        "MS": "Montserrat",
        "MZ": "Mozambique",
        "NA": "Namibia",
        "NC": "New Caledonia",
        "NI": "Nicaragua",
        "NE": "Niger",
        "NG": "Nigeria",
        "NO": "Norway",
        "OM": "Oman",
        "PK": "Pakistan",
        "PA": "Panama",
        "PG": "Papua New Guinea",
        "PE": "Peru",
        "PR": "Puerto Rico",
        "RE": "Reunion",
        "RO": "Romania",
        "RW": "Rwanda",
        "KN": "Saint Kitts and Nevis",
        "LC": "Saint Lucia",
        "VC": "Saint Vincent and the Grenadines",
        "SA": "Saudi Arabia",
        "SN": "Senegal",
        "RS": "Serbia",
        "SC": "Seychelles",
        "SL": "Sierra Leone",
        "SG": "Singapore",
        "SX": "Sint Maarten",
        "SK": "Slovakia",
        "SI": "Slovenia",
        "SB": "Solomon Islands",
        "ZA": "South Africa",
        "LK": "Sri Lanka",
        "TZ": "Tanzania, United Republic of",
        "TH": "Thailand",
        "TL": "Timor-Leste",
        "TG": "Togo",
        "TT": "Trinidad and Tobago",
        "TN": "Tunisia",
        "TM": "Turkemistan",
        "TC": "Turks and Caicos Islands",
        "AE": "United Arab Emirates",
        "UZ": "Uzbekistan",
        "VU": "Vanatu",
        "VA": "Vatican City",
        "VN": "Vietnam",
        "VG": "Virgin Islands, British",
        "ZM": "Zambia"
    },

    tier4: { // 36.0 €
        "AR": "Argentine",
        "CL*": "Chili",
        "CG": "Congo",
        "DJ": "Djibouti",
        "EG": "Egypte",
        "EC": "Equateur",
        "ET": "Ethiopie",
        "GN": "Guinée",
        "ID": "Indonésie",
        "IL": "Israël",
        "JP": "Japon",
        "JO": "Jordanie",
        "KE": "Kenya",
        "KR": "République de Corée",
        "KG": "Kirghizistan",
        "LS": "Lesotho",
        "MW": "Malawi",
        "MC": "Monaco",
        "MA": "Maroc",
        "NP": "Népal",
        "PY": "Paraguay",
        "SU": "Suriname",
        "SZ": "Swaziland / Eswatini",
        "TW": "Taïwan",
        "TR": "Turquie",
        "UG": "Ouganda",
        "UA": "Ukraine",
        "UY": "Uruguay",
        "VE": "Venezuela",
        "YE": "Yémen",
        "ZW": "Zimbabwe"
    },

    tier5: { // 5.75
        "DE": "Allemagne",
        "AT": "Autriche",
        "BE": "Belgique",
        "BG": "Bulgarie",
        "CY": "Chypre",
        "HR": "Croatie",
        "DK": "Danemark",
        "ES": "Espagne",
        "EE": "Estonie",
        "FI": "Finlande",
        "FR": "France",

        "GI": "Gibraltar",
        "GR": "Grèce",
        "HU": "Hongrie",
        "IE": "Irlande",
        "IS": "Islande",
        "IT": "Italie",
        "LV": "Lettonie",
        "LI": "Liechtenstein",
        "LT": "Lituanie",
        "LU": "Luxembourg",
        "MT": "Malta / Malte",
        "NO": "Norvège",
        "NL": "Pays-Bas",
        "PL": "Pologne",
        "PT": "Portugal",
        "CZ": "République Tchèque",
        "RO": "Roumanie",
        "GB": "Royaume-Uni",
        "SK": "Slovaquie",
        "SI": "Slovénie",
        "SE": "Suède"
    }
}

export const tierPrices = {
    tier1: 12,
    tier2: 16.5,
    tier3: 22.5,
    tier4: 36,
    tier5: 5.75,
};

export function getTierForIso(iso: string): string | undefined {
    for (const tierName in tiers) {
        if (tiers.hasOwnProperty(tierName)) {
            const tier = tiers[tierName];
            if (iso in tier) {
                return tierName;
            }
        }
    }
    return undefined;
}
